In [61]:
import pandas as pd
import numpy as np

df_raw = pd.read_csv("../data/raw/netflix_titles.csv")
df = df_raw.copy()
print("Original dataset shape:", df_raw.shape)
print("Working dataset shape:", df.shape)
df.head()

Original dataset shape: (8807, 12)
Working dataset shape: (8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [62]:
missing_count=df.isnull().sum()
missing_percentage=(df.isnull().mean()*100).round(2)

missing_summary=pd.DataFrame({'Missing Count':missing_count,'Missing Percentage':missing_percentage})
missing_summary=missing_summary[missing_summary['Missing Count']>0].sort_values('Missing Count',ascending=False)
missing_summary

            Missing Count  Missing Percentage
director             2634               29.91
country               831                9.44
cast                  825                9.37
date_added             10                0.11
rating                  4                0.05
duration                3                0.03

In [63]:
duration_issues=df.loc[df['duration'].isnull(),["show_id", "title", "type", "rating", "duration", "listed_in"]]
duration_issues

,show_id,title,type,rating,duration,listed_in
5541,s5542,Louis C.K. 2017,Movie,74 min,NaN,Movies
5794,s5795,Louis C.K.: Hilarious,Movie,84 min,NaN,Movies
5813,s5814,Louis C.K.: Live at the Comedy Store,Movie,66 min,NaN,Movies

In [64]:
# Find rating values that look like durations
suspicious_ratings = df[
    df["rating"].astype("string").str.contains(
        r"\bmin\b|\bSeason\b",
        case=False,
        na=False
    )
]
suspicious_ratings[
    ["show_id", "title", "type", "rating", "duration"]
]

     show_id                                 title   type  rating duration
5541   s5542                       Louis C.K. 2017  Movie  74 min      NaN
5794   s5795                 Louis C.K.: Hilarious  Movie  84 min      NaN
5813   s5814  Louis C.K.: Live at the Comedy Store  Movie  66 min      NaN

In [65]:
# Correct misplaced duration values
df.loc[df["show_id"] == "s5542", ["rating", "duration"]] = [np.nan, "74 min"]
df.loc[df["show_id"] == "s5795", ["rating", "duration"]] = [np.nan, "84 min"]
df.loc[df["show_id"] == "s5814", ["rating", "duration"]] = [np.nan, "66 min"]

In [66]:
df.loc[
    df["show_id"].isin(["s5542", "s5795", "s5814"]),
    ["show_id", "title", "type", "rating", "duration"]
]

     show_id                                 title   type rating duration
5541   s5542                       Louis C.K. 2017  Movie    NaN   74 min
5794   s5795                 Louis C.K.: Hilarious  Movie    NaN   84 min
5813   s5814  Louis C.K.: Live at the Comedy Store  Movie    NaN   66 min

In [67]:
df['duration'].isnull().sum()

np.int64(0)

In [68]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [69]:
df['director']=df['director'].fillna('Unknown')
df['cast']=df['cast'].fillna('Unknown')
df['country']=df['country'].fillna('Unknown')

In [70]:
df.loc[df['rating'].isnull(),["show_id", "title", "type", "rating", "duration"]]

,show_id,title,type,rating,duration
5541,s5542,Louis C.K. 2017,Movie,NaN,74 min
5794,s5795,Louis C.K.: Hilarious,Movie,NaN,84 min
5813,s5814,Louis C.K.: Live at the Comedy Store,Movie,NaN,66 min
5989,s5990,13TH: A Conversation with Oprah Winfrey & Ava ...,Movie,NaN,37 min
6827,s6828,Gargantia on the Verdurous Planet,TV Show,NaN,1 Season
7312,s7313,Little Lunch,TV Show,NaN,1 Season
7537,s7538,My Honor Was Loyalty,Movie,NaN,115 min

In [71]:
df["rating"] = df["rating"].fillna("Unknown")

In [72]:
df['date_added'].dtype

In [73]:
df["date_added"] = df["date_added"].fillna("Unknown")

In [74]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [75]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate show IDs:", df["show_id"].duplicated().sum())

Duplicate rows: 0
Duplicate show IDs: 0

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      8807 non-null   str
 4   cast          8807 non-null   str
 5   country       8807 non-null   str
 6   date_added    8807 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8807 non-null   str
 9   duration      8807 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [77]:
# Inspect unique values in important categorical columns
print("Content types:", df["type"].unique())
print("Ratings:", df["rating"].unique())
print("Release year range:", df["release_year"].min(), "-", df["release_year"].max())

Content types: <StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str
Ratings: <StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',  'Unknown',
       'NR', 'TV-Y7-FV',       'UR']
Length: 15, dtype: str
Release year range: 1925 - 2021

In [78]:
# Inspect duration formats by content type
#Movie
print("Movie duration examples:")
print(
    df.loc[df["type"] == "Movie", "duration"]
    .value_counts()
    .head(10)
)
#TV Show
print("\nTV Show duration examples:")
print(
    df.loc[df["type"] == "TV Show", "duration"]
    .value_counts()
    .head(10)
)

Movie duration examples:
duration
90 min     152
94 min     146
97 min     146
93 min     146
91 min     144
95 min     137
96 min     130
92 min     129
102 min    122
98 min     120
Name: count, dtype: int64

TV Show duration examples:
duration
1 Season      1793
2 Seasons      425
3 Seasons      199
4 Seasons       95
5 Seasons       65
6 Seasons       33
7 Seasons       23
8 Seasons       17
9 Seasons        9
10 Seasons       7
Name: count, dtype: int64

In [79]:
# Check whether durations match the expected format
movie_mask=df['type'].eq('Movie')
tv_mask=df['type'].eq('TV Show')
invalid_movies=df[
    movie_mask & ~df['duration'].str.fullmatch(r'\d+ min',na=False)
]
invalid_tv_shows=df[
    tv_mask & ~df['duration'].str.fullmatch(r'\d+ Seasons?',na=False)
]
print("Invalid movie durations:", len(invalid_movies))
print("Invalid TV Show durations:", len(invalid_tv_shows))

Invalid movie durations: 0
Invalid TV Show durations: 0

In [80]:
print('Unxpected content types:')
print(df.loc[~df['type'].isin(['Movie', 'TV Show']), 'type'].unique())

#check release years
print('\nInvalid release years:')
print(df.loc[(df['release_year']<1925) | (df['release_year']>2021),['title','release_year']])

Unxpected content types:
<StringArray>
[]
Length: 0, dtype: str

Invalid release years:
Empty DataFrame
Columns: [title, release_year]
Index: []

In [81]:
df['date_added']=pd.to_datetime(
    df['date_added'].replace('Unknown',pd.NA),
    format='%B %d, %Y',
    errors='coerce'
)
print('Data type:',df['date_added'].dtype)
print('Missing dates:',df['date_added'].isna().sum())

Data type: datetime64[us]
Missing dates: 98

In [82]:
df["date_added"] = pd.to_datetime(
    df_raw["date_added"].str.strip(),
    format="%B %d, %Y",
    errors="coerce"
)
print("Data type:", df["date_added"].dtype)
print("Missing dates:", df["date_added"].isna().sum())

Data type: datetime64[us]
Missing dates: 10

In [83]:
print(df["rating"].value_counts(dropna=False))

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
Unknown        7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [84]:
# Final dataset shape
print("Dataset shape:", df.shape)

# Check remaining missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Check duplicate records
print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (8807, 12)

Missing values per column:
show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

Duplicate rows: 0

In [85]:
# Check the dataset structure before exporting

print("Dataset shape:", df.shape)
print("Unique show IDs:", df["show_id"].nunique())

# Inspect the record around the reported error, this is the error that im getting in powerbi like i should get(8807 rows) but im getting(8809),so we are verifing this.
df[df["description"].str.contains(
    "Flying Fortress", case=False, na=False
)][["show_id", "type", "title", "date_added",
   "release_year", "rating", "duration", "description"]]

Dataset shape: (8807, 12)
Unique show IDs: 8807

,show_id,type,title,date_added,release_year,rating,duration,description
8419,s8420,Movie,The Memphis Belle: A Story of a\nFlying Fortress,2017-03-31,1944,TV-PG,40 min,This documentary centers on the crew of the B-...

In [86]:
# Inspect the record containing Flying Fortress
result = df[
    df["description"].str.contains(
        "Flying Fortress", case=False, na=False
    )
]
print(result.T.to_string())

                                                                                                                                                            8419
show_id                                                                                                                                                    s8420
type                                                                                                                                                       Movie
title                                                                                                           The Memphis Belle: A Story of a\nFlying Fortress
director                                                                                                                                           William Wyler
cast                                                                                                                                                     Unknown
country                                                                                                                                            United States
date_added                                                                                                                                   2017-03-31 00:00:00
release_year                                                                                                                                                1944
rating                                                                                                                                                     TV-PG
duration                                                                                                                                                  40 min
listed_in                                                                                                                          Classic Movies, Documentaries
description   This documentary centers on the crew of the B-17 Flying Fortress Memphis Belle as it prepares to execute a strategic bombing mission over Germany.

In [87]:
import pandas as pd

check_df = pd.read_csv(
    "../data/processed/netflix_cleaned.csv",
    encoding="utf-8"
)
print("CSV shape:", check_df.shape)
print("Unique IDs:", check_df["show_id"].nunique())
print("Duplicate rows:", check_df.duplicated().sum())
print(
    check_df[
        check_df["description"].str.contains(
            "Flying Fortress", case=False, na=False
        )
    ][["show_id", "title", "duration", "description"]]
)

CSV shape: (8807, 12)
Unique IDs: 8807
Duplicate rows: 0
     show_id                                             title duration  \
8419   s8420  The Memphis Belle: A Story of a\nFlying Fortress   40 min

                                            description
8419  This documentary centers on the crew of the B-...

In [88]:
from pathlib import Path

# Create the processed folder if it doesn't exist
Path("../data/processed").mkdir(parents=True, exist_ok=True)

# Save the cleaned dataset
df.to_csv("../data/processed/netflix_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

## Data Cleaning Summary

### Objective
The objective of this stage was to improve the quality and consistency of the Netflix dataset before performing exploratory data analysis (EDA).

### Cleaning Steps Performed
- **Missing Values:** Replaced missing values in `director`, `cast`, `country`, and `rating` with `"Unknown"`. Preserved the 10 missing `date_added` values as missing because their original dates could not be determined.
- **Data Correction:** Identified three movie records where duration values were incorrectly stored in the `rating` column and moved those values to `duration`.
- **Duplicate Checks:** Verified that there were no duplicate rows or duplicate `show_id` values.
- **Data Validation:** Checked content types, release years, rating categories, and duration formats for inconsistencies.
- **Date Conversion:** Converted `date_added` into a datetime column to support time-based analysis.

### Final Dataset Status
- Total records: 8,807
- Total columns: 12
- Duplicate rows: 0
- Missing values: 10, all in `date_added`
- Movie and TV Show duration formats: Passed validation

### Limitations
The missing values replaced with `"Unknown"` remain unknown; the original information could not be recovered. The three corrected duration values were reassigned based on the inspected records. The validation checks confirm consistency with the rules used, but do not guarantee that every source value is factually correct.

### Conclusion
The dataset is now prepared for exploratory data analysis. The original raw dataset was retained separately, and the cleaned dataset was saved as `data/processed/netflix_cleaned.csv`.